name: Called Workflow

on:
  workflow_call:
    inputs:
      latest_check:
        description: 'Check if the latest commit'
        required: false
        type: boolean
        default: false

jobs:
  check-latest-commit:
    runs-on: ubuntu-22.04
    steps:
      - name: Compare Commits
        run: |
          if [ "${{ inputs.latest_check }}" == "false" ]; then
            echo "not check latest commit"
            exit 0
          fi
          echo "CURRENT_COMMIT=${{ github.sha }}"
          LATEST_COMMIT=hoge
          echo "LATEST_COMMIT=$LATEST_COMMIT"

          # 古いcommitの場合はエラーを返す
          if [ "${{ github.sha }}" != "$LATEST_COMMIT" ]; then
            echo "The commit hash is not the latest"
            exit 1
          fi
        env:
          GH_TOKEN: ${{ github.token }}

  test-job:
    needs: check-latest-commit
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running job-1"
      - run: sleep 1  # 長時間実行するジョブをシミュレーション





  