name: Called Workflow

on:
  workflow_call:
    inputs:
      concurrency_group:
        required: true
        type: string
      cancel-in-progress:
        required: false
        type: boolean
jobs:
  job-1:
    runs-on: ubuntu-latest
    # concurrency:
    #   group: ${{ inputs.concurrency_group }}
    #   cancel-in-progress: ${{ inputs.cancel-in-progress }}
    steps:
      - run: echo "Running job-1"
      - run: sleep 1  # 長時間実行するジョブをシミュレーション



  