name: Called Workflow

on:
  workflow_call:
    inputs:
      concurrency_group:
        required: true
        type: string
      cancel-in-progress:
        required: false
        type: boolean
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running job-1"
      - run: sleep 30  # 長時間実行するジョブをシミュレーション



  