name: Build and Trigger

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger Repository Dispatch
        env:
          GITHUB_SHA: ${{ github.sha }}
          GH_TOKEN: ${{ github.token}}
        run: |
          gh api \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/dispatches \
            -f event_type="trigger-workflow" \
            -F client_payload="{\"commit_hash\":\"${GITHUB_SHA}\"}"