name: Build and Trigger

on:
  push:
    branches:
      - master

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger Dispatch Event
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo; // コンテキストからオーナーとリポジトリ名を取得
            const sha = context.sha;

            await github.rest.repos.createDispatchEvent({
              owner: owner,
              repo: repo,
              event_type: 'trigger-workflow', // イベントのタイプ
              client_payload: {
                commit_hash: sha, // 任意のペイロード
              },
            });

