name: Danger

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions: read-all

env:
  DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # NOTE: デフォルトのfetch-depth = 1だと、派生元のコミットが含まれないため、Dangerがエラーになってしまう
          # 1PRあたりせいぜい50コミット以下になると予測し、50を指定している
          fetch-depth: 50
      - name: Set up library
        run: sudo apt install mcrypt libmcrypt-dev
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.1
          bundler-cache: true
      - name: bundle install
        run: bundle install
      - name: Danger
        run: bundle exec danger --verbose