name: Danger
on: [pull_request]
permissions: write-all
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true
env:
  BUNDLE_ONLY: danger
jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # NOTE: デフォルトのfetch-depth = 1だと、派生元のコミットが含まれないため、Dangerがエラーになってしまう
          # 1PRあたりせいぜい500コミット以下になると予測し、500を指定している
          fetch-depth: 500
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
      # NOTE: 10秒程度でインストールは完了するので ruby/setup-ruby の bundle cache は使わず
      # 毎回 bundle install している
      - run: bundle install Danger
      - name: Danger
        run: bundle exec danger --verbose
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}