name: Deploy Application
run-name: "echo by @${{ github.actor }} (Commit: ${{ github.sha }})"
on:
  workflow_run:
    workflows: ["RSpec-Tests"]
    branches:
      - master
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo complete
        run: echo "complete"