name: Deploy Application

on:
  workflow_run:
    workflows: ["RSpec-Tests"]
    branches:
      - master
    types:
      - completed
concurrency:
    group: deploy-production

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo complete
        run: echo "complete"