name: release_notify

on:
  push:
    branches: 
      - master

permissions:
  contents: read
  deployments: write

jobs:
  base:
    uses: ./.github/workflows/release_notify_base.yml
  notify-authors:
    runs-on: ubuntu-latest
    needs: [base]
    timeout-minutes: 1
    steps:
    - name: Notify authors
      run: |
        # リリースPRに含まれるコミットメッセージを取得
        COMMIT_MESSAGES=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/${{ github.event.pull_request.number }}/commits" | \
            jq -r '.[].commit.message')

        # コミットメッセージからPR番号を抽出
        PR_NUMBERS=$(echo "$COMMIT_MESSAGES" | grep -o "#[0-9]*" | tr -d '#')

        # PR番号からPRの作者を取得し、コメントを投稿
        for PR_NUMBER in $PR_NUMBERS; do
          AUTHOR_LOGIN=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER" | \
            jq -r .user.login)

          curl -s -H "Authorization: token $GITHUB_TOKEN" \
            -X POST -d "{\"body\":\"@${AUTHOR_LOGIN} このPRはデプロイされました。\"}" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/comments"
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      