name: release_notify_test

on:
  pull_request:
    types: [closed]
    branches: [master]

permissions: write-all
# test2
jobs:
  notify-authors:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Notify authors using gh command
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        PR_NUM=${{ github.event.pull_request.number }}
        
        # コミットメッセージを取得
        COMMIT_MESSAGES=$(gh api repos/$GITHUB_REPOSITORY/pulls/$PR_NUM/commits --jq '.[].commit.message')

        PR_NUMBERS=$(echo "$COMMIT_MESSAGES" | grep -o "#[0-9]*" | tr -d '#')

        for PR_NUMBER in $PR_NUMBERS; do
          # PRの作者のログイン名を取得
          AUTHOR_LOGIN=$(gh api repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER --jq '.user.login')
          
          BODY_CONTENT="{\"body\":\"@${AUTHOR_LOGIN} このPRはデプロイされました。\"}"
          gh api repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/comments -X POST -f "$BODY_CONTENT"
        done
