name: Create Release PR

on:
  push:
    branches:
      - develop
permissions:
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.8

    - name: Create a release pull request
      env:
        TZ: Asia/Tokyo
        GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_PR_RELEASE_BRANCH_PRODUCTION: master
        GIT_PR_RELEASE_BRANCH_STAGING:  develop
        GIT_PR_RELEASE_TEMPLATE: .github/.git-pr-template
        GIT_PR_RELEASE_LABELS: "Waiting for Approve"
      run: |
        gem install --no-document git-pr-release -v "2.1.2"
        git-pr-release --no-fetch || echo "Done."