name: Create Release PR

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
    - uses: actions/checkout@v2
    - name: Create a release pull request
      env:
        TZ: Asia/Tokyo
        GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_PR_RELEASE_BRANCH_PRODUCTION: master
        GIT_PR_RELEASE_BRANCH_STAGING:  develop
        GIT_PR_RELEASE_TEMPLATE: .github/.git-pr-template
        GIT_PR_RELEASE_LABELS: "Waiting for Approve"
      run: |
        gh pr create --title "Pull request title" --body "Pull request body"