name: RSpec-Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for test
        run: sleep 20
