name: rspec-comment


on:
  pull_request:
  # issue_comment:
  #   types: [created]


permissions:
  contents: read
  pull-requests: write
  actions: write

jobs:
  check-comment:
    # if: github.event_name == 'issue_comment' && github.event.comment.body == '/result'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger RSpec job
        run: echo "RSpec results will be processed."

  merge-results:
    needs: check-comment
    if: github.event_name == 'pull_request' || (github.event_name == 'issue_comment' && github.event.comment.body == '/result')
    runs-on: ubuntu-latest

    steps:
      - run: |
          json_data='{
              "version": "3.13.0",
              "messages": ["Run options: exclude {:slow=true}"],
              "seed": 12345,
              "examples": [
                  {
                      "id": "./spec/requests/users_spec.rb[1:1:1]",
                      "description": "returns 200 OK",
                      "full_description": "Users GET /users returns 200 OK",
                      "status": "passed",
                      "file_path": "./spec/requests/users_spec.rb",
                      "line_number": 10,
                      "run_time": 0.200,
                      "pending_message": null
                  },
                  {
                      "id": "./spec/models/user_spec.rb[1:1:1]",
                      "description": "is valid with valid attributes",
                      "full_description": "User is valid with valid attributes",
                      "status": "passed",
                      "file_path": "./spec/models/user_spec.rb",
                      "line_number": 5,
                      "run_time": 0.150,
                      "pending_message": null
                  },
                  {
                      "id": "./spec/controllers/sessions_controller_spec.rb[1:1:1]",
                      "description": "redirects to the user page on successful login",
                      "full_description": "SessionsController POST /login redirects to the user page on successful login",
                      "status": "passed",
                      "file_path": "./spec/controllers/sessions_controller_spec.rb",
                      "line_number": 20,
                      "run_time": 0.250,
                      "pending_message": null
                  },
                  {
                      "id": "./spec/features/login_spec.rb[1:1:1]",
                      "description": "shows error message on failed login",
                      "full_description": "Login shows error message on failed login",
                      "status": "pending",
                      "file_path": "./spec/features/login_spec.rb",
                      "line_number": 30,
                      "run_time": 0.000,
                      "pending_message": "Not yet implemented"
                  }
              ],
              "profile": {
                  "examples": [
                      {
                          "id": "./spec/requests/users_spec.rb[1:1:1]",
                          "description": "returns 200 OK",
                          "full_description": "Users GET /users returns 200 OK",
                          "status": "passed",
                          "file_path": "./spec/requests/users_spec.rb",
                          "line_number": 10,
                          "run_time": 0.200,
                          "pending_message": null
                      },
                      {
                          "id": "./spec/models/user_spec.rb[1:1:1]",
                          "description": "is valid with valid attributes",
                          "full_description": "User is valid with valid attributes",
                          "status": "passed",
                          "file_path": "./spec/models/user_spec.rb",
                          "line_number": 5,
                          "run_time": 0.150,
                          "pending_message": null
                      },
                      {
                          "id": "./spec/controllers/sessions_controller_spec.rb[1:1:1]",
                          "description": "redirects to the user page on successful login",
                          "full_description": "SessionsController POST /login redirects to the user page on successful login",
                          "status": "passed",
                          "file_path": "./spec/controllers/sessions_controller_spec.rb",
                          "line_number": 20,
                          "run_time": 0.250,
                          "pending_message": null
                      },
                      {
                          "id": "./spec/features/login_spec.rb[1:1:1]",
                          "description": "shows error message on failed login",
                          "full_description": "Login shows error message on failed login",
                          "status": "pending",
                          "file_path": "./spec/features/login_spec.rb",
                          "line_number": 30,
                          "run_time": 0.000,
                          "pending_message": "Not yet implemented"
                      }
                  ],
                  "slowest": 0.250,
                  "total": 0.600
              },
              "summary": {
                  "duration": 1,
                  "example_count": 4,
                  "failure_count": 0,
                  "pending_count": 1,
                  "errors_outside_of_examples_count": 0
              },
              "summary_line": "4 examples, 0 failures, 1 pending"
          }'

          echo "$json_data" > merged_rspec_results.json
      - name: RSpec Report
        uses: SonicGarden/rspec-report-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          json-path: merged_rspec_results.json
