name: rspec-comment

on:
  push:

permissions:
  contents: read
  pull-requests: write
  actions: write

jobs:
  check-comment:
    if: github.event_name == 'issue_comment' && github.event.comment.body == '/result'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger RSpec job
        run: echo "RSpec results will be processed."

  merge-results:
    # needs: check-comment
    # if: github.event_name == 'pull_request' || (github.event_name == 'issue_comment' && github.event.comment.body == '/result')
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - run: ls | grep test_data.json
      - name: RSpec Report
        uses: hirosi1900day/test-report@v1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          json-path: test_data.json
          pr-number: "125"
