name: Caller Workflow

on:
  push:

jobs:
  call-workflow: 
    uses: ./.github/workflows/_test.yml
    concurrency:
      group: test
      cancel-in-progress: true

  job3:
    needs: call-workflow
    uses: ./.github/workflows/_test2.yml
    concurrency:
      group: test2
      cancel-in-progress: false

