name: Caller Workflow

on:
  push:

jobs:
  call-workflow: 
    uses: ./.github/workflows/_test.yml
    concurrency:
      group: test
      cancel-in-progress: true

  job3:
    needs: call-workflow
    uses: ./.github/workflows/_test2.yml
    with:
      concurrency_group: example-group2

