name: Caller Workflow

on:
  push:

jobs:
  call-workflow: 
    uses: ./.github/workflows/_test.yml

  call-workflow2: 
    uses: ./.github/workflows/_test.yml
    with:
      latest_check: true
     

