name: Caller Workflow

on:
  push:

jobs:
  call-workflow: 
    uses: ./.github/workflows/_test.yml
    with:
      latest_check: true

  call-workflow2: 
    uses: ./.github/workflows/_test2.yml
    # with:
    #   latest_check: true

  test:
    needs: [call-workflow, call-workflow2]
    if: ${{ (success() || failure()) && needs.call-workflow.outputs.deployed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running job-1"
      - run: sleep 1  # 長時間実行するジョブをシミュレーション
     

