name: Caller Workflow

on:
  push:

jobs:
  call-workflow: 
    uses: ./.github/workflows/_test.yml
    with:
      concurrency_group: example-group
      cancel-in-progress: true

  job3:
    runs-on: ubuntu-latest
    needs: call-workflow
    steps:
      - run: echo "Running job3"
      - run: sleep 30  # 長時間実行するジョブをシミュレーション
      