name: Caller Workflow

on:
  push:

jobs:
  call-workflow: 
    uses: ./.github/workflows/_test.yml
    with:
      concurrency_group: example-group
      cancel-in-progress: true

  job3:
    uses: ./.github/workflows/_test2.yml
    with:
      concurrency_group: example-group2
