name: Test2

on:
  push:

permissions: write-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test2:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@v3
    - name: Add commit status
      uses: octodemo-resources/github-commit-status@v1
      with:
        context: unit_test_results
        state: success
        description: Tests passed
        target_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}