name: Update File and Create PR

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update file with merge commit hash
        run: |
          echo "Updating with merge commit hash: ${{ github.event.client_payload.commit_hash }}"
          echo "${{ github.event.client_payload.commit_hash }}" > merge_commit.txt
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b update-merge-commit
          git add merge_commit.txt
          git commit -m "Update merge commit hash to ${{ github.event.inputs.merge_commit }}"

      - name: Push changes
        run: git push -f origin update-merge-commit

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: update-merge-commit
          title: "Update merge commit hash"
          body: |
            This PR updates the merge commit hash to `${{ github.event.inputs.merge_commit }}`
